
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace BlogPostsFormsProject.Models
{
    public partial class Blogs
    {
        public Blogs()
        {
            Posts = new HashSet<Posts>();
        }

        public int BlogId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public DateTime? DateModified { get; set; }

        public virtual ICollection<Posts> Posts { get; set; }

        public void Deconstruct(out int identifier, out string name, out string url, out string title, out DateTime? dateTime)
        {
            identifier = BlogId;
            name = Name;
            url = Url;
            title = Title;
            dateTime = DateModified;
        }
        public void Deconstruct(out int identifier, out string name, out string url, out string title)
        {
            identifier = BlogId;
            name = Name;
            url = Url;
            title = Title;
        }
    }

}