// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlogPostsFormsProject.Models
{
    public partial class PostTag
    {
        public int PostsId { get; set; }
        public string TagsId { get; set; }

        public virtual Posts Posts { get; set; }
        public virtual Tags Tags { get; set; }
    }
}