// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlogPostsFormsProject.Models
{
    public partial class Tags
    {
        public Tags()
        {
            PostTag = new HashSet<PostTag>();
        }

        public string TagId { get; set; }

        public virtual ICollection<PostTag> PostTag { get; set; }
    }
}