// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlogPostsFormsProject.Data;
using BlogPostsFormsProject.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace BlogPostsFormsProject.Data.Configurations
{
    public partial class BlogsConfiguration : IEntityTypeConfiguration<Blogs>
    {
        public void Configure(EntityTypeBuilder<Blogs> entity)
        {
            entity.HasKey(e => e.BlogId)
                .HasName("PK_dbo.Blogs");

            entity.Property(e => e.DateModified).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Name).HasMaxLength(200);

            entity.Property(e => e.Url).HasMaxLength(200);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Blogs> entity);
    }
}
