// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlogPostsFormsProject.Data;
using BlogPostsFormsProject.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace BlogPostsFormsProject.Data.Configurations
{
    public partial class PostTagConfiguration : IEntityTypeConfiguration<PostTag>
    {
        public void Configure(EntityTypeBuilder<PostTag> entity)
        {
            entity.HasKey(e => new { e.PostsId, e.TagsId });

            entity.HasOne(d => d.Posts)
                .WithMany(p => p.PostTag)
                .HasForeignKey(d => d.PostsId);

            entity.HasOne(d => d.Tags)
                .WithMany(p => p.PostTag)
                .HasForeignKey(d => d.TagsId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PostTag> entity);
    }
}
