// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlogPostsFormsProject.Data;
using BlogPostsFormsProject.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace BlogPostsFormsProject.Data.Configurations
{
    public partial class PostsConfiguration : IEntityTypeConfiguration<Posts>
    {
        public void Configure(EntityTypeBuilder<Posts> entity)
        {
            entity.HasKey(e => e.PostId)
                .HasName("PK_dbo.Posts");

            entity.Property(e => e.Content).HasColumnType("ntext");

            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.Blog)
                .WithMany(p => p.Posts)
                .HasForeignKey(d => d.BlogId)
                .HasConstraintName("FK_dbo.Posts_dbo.Blogs_BlogId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Posts> entity);
    }
}
