// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlogPostsFormsProject.Data;
using BlogPostsFormsProject.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace BlogPostsFormsProject.Data.Configurations
{
    public partial class TagsConfiguration : IEntityTypeConfiguration<Tags>
    {
        public void Configure(EntityTypeBuilder<Tags> entity)
        {
            entity.HasKey(e => e.TagId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tags> entity);
    }
}
